ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.blank-imports]
    Exclude=["TEST"]
[rule.context-as-argument]
    Exclude=["TEST"]
[rule.context-keys-type]
    Exclude=["TEST"]
[rule.dot-imports]
    Exclude=["TEST"]
[rule.error-return]
    Exclude=["TEST"]
[rule.error-strings]
    Exclude=["TEST"]
[rule.error-naming]
    Exclude=["TEST"]
[rule.exported]
    Exclude=["TEST"]
[rule.increment-decrement]
    Exclude=["TEST"]
[rule.var-declaration]
    Exclude=["TEST"]
[rule.package-comments]
    Exclude=["TEST"]
[rule.range]
    Exclude=["TEST"]
[rule.receiver-naming]
    Exclude=["TEST"]
[rule.time-naming]
    Exclude=["TEST"]
[rule.unexported-return]
    Exclude=["TEST"]
[rule.indent-error-flow]
    Exclude=["TEST"]
[rule.errorf]
    Exclude=["TEST"]
[rule.empty-block]
    Exclude=["TEST"]
[rule.superfluous-else]
    Exclude=["TEST"]
[rule.unused-parameter]
    Exclude=["TEST"]
[rule.unreachable-code]
    Exclude=["TEST"]
[rule.redefines-builtin-id]
    Exclude=["TEST"]

[rule.var-naming]
    arguments = [["ID"], ["VM"], [{upperCaseConst=true}]]
    Exclude=["TEST"]
